name: sight_proj
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  firebase_core_dart: ^1.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_scalable_ocr: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^3.8.5
  get: ^4.6.6
  google_mlkit_text_recognition: ^0.6.0
  lite_rolling_switch: ^1.0.1
  permission_handler: ^11.3.1
  usb_serial: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Jost

      fonts:
        - asset: fonts/Jost-600-Semi.ttf
