name: sight_proj
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  camera: ^0.10.5+9
  controller: ^0.1.12
  cupertino_icons: ^1.0.6
  firebase_ml_custom: ^0.2.0+3
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_face_api_beta: ^0.0.121
  flutter_localization: ^0.2.0
  flutter_mjpeg: ^2.0.4
  flutter_tflite: ^1.0.0
  flutter_tts: ^4.0.0
  flutter_vision: ^1.1.4
  get: ^4.6.6
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_text_recognition: ^0.13.0
  image: ^3.2.0
  image_gallery_saver: ^2.0.3
  image_picker: ^0.8.5+3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinch_zoom_image_last: ^0.4.1
  provider: ^6.1.2
  screenshot: ^3.0.0
  sqflite: ^2.3.3+1
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/imageclass.tflite
    - assets/labels.txt

  fonts:
    - family: Jost

      fonts:
        - asset: fonts/Jost-600-Semi.ttf
