// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3S0POrCqA6mpcJgrZeDJY70jz9Ndmupo',
    appId: '1:741303325130:web:ed5a65c90f9f137c1cff33',
    messagingSenderId: '741303325130',
    projectId: 'sightseer-project',
    authDomain: 'sightseer-project.firebaseapp.com',
    storageBucket: 'sightseer-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5wWiGOP4yf_1800G_gRwdHgm_ezWYKg',
    appId: '1:741303325130:android:338e3c4d39f7550d1cff33',
    messagingSenderId: '741303325130',
    projectId: 'sightseer-project',
    storageBucket: 'sightseer-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNad3hQdIQ691BIY0FFGLRZjrovMfQMg',
    appId: '1:741303325130:ios:c57b46b95dc0200e1cff33',
    messagingSenderId: '741303325130',
    projectId: 'sightseer-project',
    storageBucket: 'sightseer-project.appspot.com',
    iosBundleId: 'com.example.sightProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSNad3hQdIQ691BIY0FFGLRZjrovMfQMg',
    appId: '1:741303325130:ios:c57b46b95dc0200e1cff33',
    messagingSenderId: '741303325130',
    projectId: 'sightseer-project',
    storageBucket: 'sightseer-project.appspot.com',
    iosBundleId: 'com.example.sightProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3S0POrCqA6mpcJgrZeDJY70jz9Ndmupo',
    appId: '1:741303325130:web:2109def3fea68cfe1cff33',
    messagingSenderId: '741303325130',
    projectId: 'sightseer-project',
    authDomain: 'sightseer-project.firebaseapp.com',
    storageBucket: 'sightseer-project.appspot.com',
  );
}